name: My First WorkFlow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome message
        run: echo "Hello all"

      - name: List Files
        run: ls

      - name: ReadFile
        run: cat README.md

      - name: get date
        run: echo "today is `date`"